language: android

jdk:
  oraclejdk7
  oraclejdk8

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

script:
    - ./gradlew clean test